worktree:
  sync_branch: false
  symlink:
    - .deps/src
    - xr/addons/godotopenxrvendors/.bin
    - xr/android/build/.gradle
    - xr/.gradle
    - web/node_modules
    - python/.venv

icon: ../xr/icon.png
