worktree:
  sync_branch: false
  symlink:
    - .deps/src
    - xr/addons/godotopenxrvendors/.bin
    - xr/android/build/local.properties
    - xr/android/build/.gradle
    - xr/.gradle
    - examples/mujuco-arm-so101/.venv
    - web/node_modules

icon: ../xr/icon.png
