// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

include "pose.fbs";
include "timestamp.fbs";

namespace core;

struct ControllerInputState {
    primary_click: bool;
    secondary_click: bool;
    thumbstick_click: bool;
    menu_click: bool;
    thumbstick_x: float32;
    thumbstick_y: float32;
    squeeze_value: float32;
    trigger_value: float32;
}

struct ControllerPose {
    pose: Pose;
    is_valid: bool;
}

table ControllerSnapshot {
    grip_pose: ControllerPose (id: 0);
    aim_pose: ControllerPose (id: 1);
    inputs: ControllerInputState (id: 2);
}

table ControllerSnapshotTracked {
    data: ControllerSnapshot (id: 0);
}

table ControllerSnapshotRecord {
    data: ControllerSnapshot (id: 0);
    timestamp: DeviceDataTimestamp (id: 1);
}

root_type ControllerSnapshotRecord;
