"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

interface Props {
  /** What we're waiting for — drives the headline + ETA string. */
  worker: "preview" | "rrd";
  /** ISO-8601 timestamp from when the media artifact landed, so we
   *  can show "started Ns ago". Use `session.artifacts.media.storedAt`. */
  startedAtIso: string;
  /** Source media size in bytes — used to scale the ETA estimate. */
  mediaBytes: number;
}

/**
 * Two-line placeholder that replaces the static "still being
 * generated" text. Ticks every second so the user sees seconds
 * elapsing, and offers a manual refresh button.
 *
 * SSE-based auto-refresh (see SessionLiveRefresh.tsx) is the primary
 * path — this indicator is purely visual reassurance for the
 * 10-90 second window the worker takes. If the SSE stream is broken
 * or the worker crashed silently, the manual refresh becomes the
 * escape hatch.
 *
 * The ETA hints are empirical, measured against captures we have on
 * hand. They're not promises — long recordings or low-end hardware
 * will exceed them. We deliberately quote a RANGE so the user isn't
 * "10 seconds late" surprised by a 25-second finish.
 */
export function WorkerPendingIndicator({
  worker,
  startedAtIso,
  mediaBytes,
}: Props) {
  const router = useRouter();
  const startedAt = new Date(startedAtIso).getTime();
  const [now, setNow] = useState(() => Date.now());

  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, []);

  const elapsedSec = Math.max(0, Math.floor((now - startedAt) / 1000));
  const eta = estimateEta(worker, mediaBytes);
  const label = worker === "preview" ? "RGB preview MP4" : "Rerun .rrd";

  return (
    <div style={{ display: "grid", gap: 8 }}>
      <p style={{ fontSize: 13, margin: 0 }}>
        {label} is being generated by the post-ingest worker…
      </p>
      <p style={{ fontSize: 12, color: "var(--muted)", margin: 0 }}>
        Elapsed{" "}
        <span style={{ fontVariantNumeric: "tabular-nums" }}>
          {formatSec(elapsedSec)}
        </span>
        {" · "}
        typical {eta} for this size
        {elapsedSec > parseEtaMaxSec(eta) * 2 && (
          <>
            {" · "}
            <span style={{ color: "var(--warn)" }}>
              taking longer than expected — check server log
            </span>
          </>
        )}
      </p>
      <div>
        <button
          type="button"
          onClick={() => router.refresh()}
          style={{ fontSize: 12, padding: "4px 10px" }}
        >
          Refresh now
        </button>
      </div>
    </div>
  );
}

function formatSec(s: number): string {
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  const r = s % 60;
  return `${m}m${r.toString().padStart(2, "0")}s`;
}

// Rough empirical numbers. preview is a remux/crop — bounded by IO +
// libx264 ultrafast on the cropped half-width stream. rerun is bound
// by HEVC decode + PyAV demux + Rerun log; dominated by frame count.
function estimateEta(
  worker: "preview" | "rrd",
  mediaBytes: number,
): string {
  const mb = mediaBytes / (1024 * 1024);
  if (worker === "preview") {
    // ~25 MB/s observed for ultrafast + crop on Apple Silicon.
    const sec = Math.max(2, Math.round(mb / 25));
    return `${sec}-${sec * 2}s`;
  }
  // rrd: dominated by HEVC decode + per-frame log. ~1 second of wall
  // time per MB of source, give or take. 23 MB clip in our smoke
  // landed in 30s — within this band.
  const lo = Math.max(20, Math.round(mb * 0.8));
  const hi = Math.round(mb * 1.8);
  return `${lo}-${hi}s`;
}

function parseEtaMaxSec(eta: string): number {
  const m = /-(\d+)s/.exec(eta);
  return m && m[1] ? Number.parseInt(m[1], 10) : 60;
}
