"""Generated from specs/blueprint/v1.json. Do not edit."""

SPEC_SHA256 = "85fc4ff0499ed3dbc3949778f9d5ba57806c2ab5632693be909108af1e4395b2"
SPEC_VERSION = 1
SPEC = {'schema': 'operator.blueprint_primitive_spec.v1',
 'version': 1,
 'wire': {'capability': 'blueprint_v1',
          'spec_hash_capability': 'blueprint_spec_sha256',
          'blueprint_schema': 'operator.blueprint.v1',
          'state_schema': 'operator.blueprint_state.v1',
          'event_schema': 'operator.blueprint_event.v1',
          'commands': {'blueprint': 'Blueprint',
                       'state': 'BlueprintState',
                       'event': 'BlueprintEvent'}},
 'limits': {'components': 256, 'state_values': 1024, 'wire_integer_max': 9223372036854775807},
 'value_type_conformance': {'boolean': {'valid': [True, False], 'invalid': [0, 1, 'true', None]},
                            'string': {'valid': ['', 'ready'], 'invalid': [0, True, None, []]},
                            'integer': {'valid': [0, -1, 1.0], 'invalid': [1.5, True, '1', None]},
                            'number': {'valid': [0, -1, 1.5], 'invalid': [True, '1', None, []]},
                            'color': {'valid': ['#fff',
                                                '#ffffff',
                                                '#ffffffff',
                                                [1, 0.5, 0],
                                                [1.0, 0.5, 0.0, 1.0]],
                                      'invalid': ['red',
                                                  '#12',
                                                  '#gggggg',
                                                  True,
                                                  [1, 0],
                                                  [1, 0, 'blue'],
                                                  None]},
                            'color_map': {'valid': [{},
                                                    {'active': '#00ff00', 'error': [1, 0, 0, 1]}],
                                          'invalid': [[], {'active': True}, None]},
                            'number_array': {'valid': [[], [0, 1.5, -2]],
                                             'invalid': [0, [1, True], ['1'], None]},
                            'integer_array': {'valid': [[], [0, 1.0, -2]],
                                              'invalid': [0, [1.5], [True], None]},
                            'string_array': {'valid': [[], ['left_knee_joint', 'right_knee_joint']],
                                             'invalid': ['joint', [0], [True], None]}},
 'wire_integer_conformance': {'valid': [0, 1, 9223372036854775807],
                              'invalid': [-1, 1.0, True, '1', None]},
 'anchors': {'world': {'tracking': 'origin'},
             'head': {'tracking': 'head'},
             'left_controller': {'tracking': 'controller'},
             'right_controller': {'tracking': 'controller'},
             'left_palm': {'tracking': 'hand'},
             'right_palm': {'tracking': 'hand'}},
 'transform': {'position': {'type': 'vector3', 'default': [0.0, 0.0, 0.0]},
               'rotation': {'type': 'quaternion', 'default': [0.0, 0.0, 0.0, 1.0]},
               'scale': {'type': 'positive_vector3', 'default': [1.0, 1.0, 1.0]}},
 'primitives': {'ground_grid': {'host': 'node3d',
                                'implementation': 'ground_grid',
                                'singleton': False,
                                'default_anchor': 'world',
                                'anchors': ['world'],
                                'user_visibility_override': True,
                                'properties': {'visible': {'type': 'boolean', 'default': True},
                                               'settings_label': {'type': 'string', 'default': ''},
                                               'size': {'type': 'number',
                                                        'default': 8,
                                                        'minimum': 1,
                                                        'maximum': 40},
                                               'spacing': {'type': 'number',
                                                           'default': 0.5,
                                                           'minimum': 0.1,
                                                           'maximum': 5},
                                               'major_every': {'type': 'integer',
                                                               'default': 5,
                                                               'minimum': 2,
                                                               'maximum': 10},
                                               'line_width': {'type': 'number',
                                                              'default': 0.01,
                                                              'minimum': 0.001,
                                                              'maximum': 0.05},
                                               'color': {'type': 'color', 'default': '#8094aa66'},
                                               'major_color': {'type': 'color',
                                                               'default': '#b7cee099'},
                                               'placement_target': {'type': 'string',
                                                                    'default': ''}},
                                'bindings': {'visible': {'type': 'boolean', 'required': False}},
                                'events': {}},
                'model_lighting': {'host': 'node3d',
                                   'implementation': 'model_lighting',
                                   'singleton': True,
                                   'default_anchor': 'world',
                                   'anchors': ['world'],
                                   'user_visibility_override': True,
                                   'properties': {'visible': {'type': 'boolean', 'default': True},
                                                  'settings_label': {'type': 'string',
                                                                     'default': ''},
                                                  'key_energy': {'type': 'number',
                                                                 'default': 1.6,
                                                                 'minimum': 0,
                                                                 'maximum': 4},
                                                  'fill_energy': {'type': 'number',
                                                                  'default': 0.6,
                                                                  'minimum': 0,
                                                                  'maximum': 2},
                                                  'key_color': {'type': 'color',
                                                                'default': '#fff4e8'},
                                                  'fill_color': {'type': 'color',
                                                                 'default': '#d7e7ff'}},
                                   'bindings': {'visible': {'type': 'boolean', 'required': False},
                                                'key_energy': {'type': 'number',
                                                               'required': False,
                                                               'minimum': 0,
                                                               'maximum': 4},
                                                'fill_energy': {'type': 'number',
                                                                'required': False,
                                                                'minimum': 0,
                                                                'maximum': 2}},
                                   'events': {}},
                'robot_model': {'host': 'node3d',
                                'implementation': 'robot_model',
                                'singleton': False,
                                'default_anchor': 'world',
                                'anchors': ['world'],
                                'user_visibility_override': True,
                                'properties': {'visible': {'type': 'boolean', 'default': True},
                                               'settings_label': {'type': 'string', 'default': ''},
                                               'asset_sha256': {'type': 'string', 'required': True},
                                               'asset_size': {'type': 'integer',
                                                              'required': True,
                                                              'minimum': 20,
                                                              'maximum': 67108864},
                                               'asset_port': {'type': 'integer',
                                                              'required': True,
                                                              'minimum': 1,
                                                              'maximum': 65535},
                                               'joint_names': {'type': 'string_array',
                                                               'required': True},
                                               'smoothing_ms': {'type': 'number',
                                                                'default': 40,
                                                                'minimum': 0,
                                                                'maximum': 1000},
                                               'stale_after_ms': {'type': 'number',
                                                                  'default': 500,
                                                                  'minimum': 50,
                                                                  'maximum': 10000}},
                                'bindings': {'visible': {'type': 'boolean', 'required': False},
                                             'joint_positions': {'type': 'number_array',
                                                                 'required': True},
                                             'base_pose': {'type': 'number_array',
                                                           'length': 7,
                                                           'required': True},
                                             'sample': {'type': 'integer',
                                                        'minimum': 0,
                                                        'required': True,
                                                        'semantics': 'refresh_token'}},
                                'events': {}},
                'label': {'host': 'node3d',
                          'implementation': 'label',
                          'singleton': False,
                          'default_anchor': 'world',
                          'anchors': ['world',
                                      'head',
                                      'left_controller',
                                      'right_controller',
                                      'left_palm',
                                      'right_palm'],
                          'user_visibility_override': True,
                          'properties': {'visible': {'type': 'boolean', 'default': True},
                                         'settings_label': {'type': 'string', 'default': ''},
                                         'text': {'type': 'string', 'default': ''},
                                         'font_size': {'type': 'integer',
                                                       'default': 32,
                                                       'minimum': 8,
                                                       'maximum': 96},
                                         'pixel_size': {'type': 'number',
                                                        'default': 0.0015,
                                                        'minimum': 0.0002,
                                                        'maximum': 0.01},
                                         'outline_size': {'type': 'integer',
                                                          'default': 6,
                                                          'minimum': 0,
                                                          'maximum': 24},
                                         'no_depth_test': {'type': 'boolean', 'default': True},
                                         'color': {'type': 'color', 'default': '#ffffff'}},
                          'bindings': {'visible': {'type': 'boolean', 'required': False},
                                       'text': {'type': 'string', 'required': False},
                                       'color': {'type': 'color', 'required': False}},
                          'events': {}},
                'status_lamp': {'host': 'node3d',
                                'implementation': 'status_lamp',
                                'singleton': False,
                                'default_anchor': 'world',
                                'anchors': ['world',
                                            'head',
                                            'left_controller',
                                            'right_controller',
                                            'left_palm',
                                            'right_palm'],
                                'user_visibility_override': True,
                                'properties': {'visible': {'type': 'boolean', 'default': True},
                                               'settings_label': {'type': 'string', 'default': ''},
                                               'text': {'type': 'string', 'default': ''},
                                               'font_size': {'type': 'integer',
                                                             'default': 24,
                                                             'minimum': 8,
                                                             'maximum': 72},
                                               'pixel_size': {'type': 'number',
                                                              'default': 0.001,
                                                              'minimum': 0.0002,
                                                              'maximum': 0.01},
                                               'radius': {'type': 'number',
                                                          'default': 0.012,
                                                          'minimum': 0.003,
                                                          'maximum': 0.05},
                                               'colors': {'type': 'color_map', 'default': {}},
                                               'pulse_states': {'type': 'string_array',
                                                                'default': []},
                                               'pulse_hz': {'type': 'number',
                                                            'default': 2,
                                                            'minimum': 0.5,
                                                            'maximum': 8}},
                                'bindings': {'visible': {'type': 'boolean', 'required': False},
                                             'state': {'type': 'string', 'required': True},
                                             'text': {'type': 'string', 'required': False}},
                                'events': {}},
                'menu_item': {'host': 'system_menu',
                              'implementation': 'menu_item',
                              'singleton': False,
                              'default_anchor': 'world',
                              'anchors': ['world'],
                              'user_visibility_override': True,
                              'properties': {'visible': {'type': 'boolean', 'default': True},
                                             'settings_label': {'type': 'string', 'default': ''},
                                             'title': {'type': 'string', 'required': True},
                                             'action': {'type': 'string', 'required': True},
                                             'item_key': {'type': 'string', 'default': ''},
                                             'locked_text': {'type': 'string', 'default': 'Enable'},
                                             'unlocked_text': {'type': 'string',
                                                               'default': 'Disable'},
                                             'unavailable_text': {'type': 'string',
                                                                  'default': 'Unavailable'}},
                              'bindings': {'visible': {'type': 'boolean', 'required': False},
                                           'value': {'type': 'boolean', 'required': True},
                                           'available': {'type': 'boolean', 'required': False}},
                              'events': {'action': {'action_property': 'action',
                                                    'value_type': 'boolean'}}},
                'controller_menu': {'host': 'system_menu',
                                    'implementation': 'controller_menu',
                                    'singleton': True,
                                    'default_anchor': 'left_controller',
                                    'anchors': ['left_controller'],
                                    'user_visibility_override': True,
                                    'properties': {'visible': {'type': 'boolean', 'default': True},
                                                   'settings_label': {'type': 'string',
                                                                      'default': ''},
                                                   'title': {'type': 'string', 'required': True},
                                                   'action': {'type': 'string', 'required': True},
                                                   'locked_text': {'type': 'string',
                                                                   'default': 'Unlock'},
                                                   'unlocked_text': {'type': 'string',
                                                                     'default': 'Lock'},
                                                   'unavailable_text': {'type': 'string',
                                                                        'default': 'Unavailable'},
                                                   'secondary_action': {'type': 'string',
                                                                        'default': ''},
                                                   'secondary_text': {'type': 'string',
                                                                      'default': ''},
                                                   'item_key': {'type': 'string', 'default': ''},
                                                   'secondary_item_key': {'type': 'string',
                                                                          'default': ''}},
                                    'bindings': {'visible': {'type': 'boolean', 'required': False},
                                                 'value': {'type': 'boolean', 'required': True},
                                                 'available': {'type': 'boolean',
                                                               'required': False},
                                                 'secondary_available': {'type': 'boolean',
                                                                         'required': False},
                                                 'detail': {'type': 'string', 'required': False}},
                                    'events': {'action': {'action_property': 'action',
                                                          'value_type': 'boolean'},
                                               'secondary_action': {'action_property': 'secondary_action',
                                                                    'value_type': 'boolean'}}},
                'input_binding': {'host': 'node3d',
                                  'implementation': 'input_binding',
                                  'singleton': True,
                                  'default_anchor': 'world',
                                  'anchors': ['world'],
                                  'user_visibility_override': False,
                                  'properties': {'visible': {'type': 'boolean', 'default': True},
                                                 'settings_label': {'type': 'string',
                                                                    'default': ''},
                                                 'gesture': {'type': 'string',
                                                             'default': 'dual_trigger_hold'},
                                                 'action': {'type': 'string', 'required': True},
                                                 'hold_seconds': {'type': 'number',
                                                                  'default': 1,
                                                                  'minimum': 0.5,
                                                                  'maximum': 5},
                                                 'ack_timeout_seconds': {'type': 'number',
                                                                         'default': 3,
                                                                         'minimum': 0.5,
                                                                         'maximum': 10},
                                                 'target_component': {'type': 'string',
                                                                      'default': ''}},
                                  'bindings': {'visible': {'type': 'boolean', 'required': False},
                                               'available': {'type': 'boolean', 'required': True},
                                               'required': {'type': 'boolean', 'required': True},
                                               'acknowledged_request': {'type': 'string',
                                                                        'required': True},
                                               'success': {'type': 'boolean', 'required': True},
                                               'message': {'type': 'string', 'required': False}},
                                  'events': {'action': {'action_property': 'action',
                                                        'value_type': 'string'}}},
                'palm_menu': {'host': 'system_menu',
                              'implementation': 'palm_menu',
                              'singleton': False,
                              'default_anchor': 'left_palm',
                              'anchors': ['left_palm', 'right_palm'],
                              'user_visibility_override': True,
                              'properties': {'visible': {'type': 'boolean', 'default': True},
                                             'settings_label': {'type': 'string', 'default': ''},
                                             'title': {'type': 'string', 'required': True},
                                             'action': {'type': 'string', 'required': True},
                                             'item_key': {'type': 'string', 'default': ''},
                                             'locked_text': {'type': 'string', 'default': 'Unlock'},
                                             'unlocked_text': {'type': 'string', 'default': 'Lock'},
                                             'unavailable_text': {'type': 'string',
                                                                  'default': 'Unavailable'}},
                              'bindings': {'visible': {'type': 'boolean', 'required': False},
                                           'value': {'type': 'boolean', 'required': True},
                                           'available': {'type': 'boolean', 'required': False}},
                              'events': {'action': {'action_property': 'action',
                                                    'value_type': 'boolean'}}},
                'fingertip_tactile': {'host': 'node3d',
                                      'implementation': 'fingertip_tactile',
                                      'singleton': False,
                                      'default_anchor': 'world',
                                      'anchors': ['world'],
                                      'user_visibility_override': True,
                                      'properties': {'visible': {'type': 'boolean',
                                                                 'default': True},
                                                     'settings_label': {'type': 'string',
                                                                        'default': ''}},
                                      'bindings': {'visible': {'type': 'boolean',
                                                               'required': False},
                                                   'left_normal': {'type': 'number_array',
                                                                   'length': 5,
                                                                   'required': False},
                                                   'left_tangential': {'type': 'number_array',
                                                                       'length': 5,
                                                                       'required': False},
                                                   'left_direction': {'type': 'number_array',
                                                                      'length': 5,
                                                                      'required': False},
                                                   'left_proximity': {'type': 'number_array',
                                                                      'length': 5,
                                                                      'required': False},
                                                   'left_status': {'type': 'integer_array',
                                                                   'length': 5,
                                                                   'required': False},
                                                   'right_normal': {'type': 'number_array',
                                                                    'length': 5,
                                                                    'required': False},
                                                   'right_tangential': {'type': 'number_array',
                                                                        'length': 5,
                                                                        'required': False},
                                                   'right_direction': {'type': 'number_array',
                                                                       'length': 5,
                                                                       'required': False},
                                                   'right_proximity': {'type': 'number_array',
                                                                       'length': 5,
                                                                       'required': False},
                                                   'right_status': {'type': 'integer_array',
                                                                    'length': 5,
                                                                    'required': False},
                                                   'sample': {'type': 'integer',
                                                              'minimum': 0,
                                                              'required': False,
                                                              'semantics': 'refresh_token'}},
                                      'binding_groups': {'left_hand': ['left_normal',
                                                                       'left_tangential',
                                                                       'left_direction',
                                                                       'left_proximity',
                                                                       'left_status'],
                                                         'right_hand': ['right_normal',
                                                                        'right_tangential',
                                                                        'right_direction',
                                                                        'right_proximity',
                                                                        'right_status']},
                                      'constraints': {'at_least_one_complete_binding_group': True},
                                      'events': {}},
                'video_panel': {'host': 'external_view',
                                'implementation': 'video_panel',
                                'singleton': True,
                                'default_anchor': 'world',
                                'anchors': ['world'],
                                'user_visibility_override': True,
                                'properties': {'visible': {'type': 'boolean', 'default': True},
                                               'settings_label': {'type': 'string', 'default': ''},
                                               'follow_camera': {'type': 'boolean',
                                                                 'default': True},
                                               'distance': {'type': 'number',
                                                            'default': 3.0,
                                                            'minimum': 0.1,
                                                            'maximum': 20.0}},
                                'bindings': {'visible': {'type': 'boolean', 'required': False},
                                             'follow_camera': {'type': 'boolean',
                                                               'required': False},
                                             'system_performance_text': {'type': 'string',
                                                                         'required': False},
                                             'status_state': {'type': 'string', 'required': False},
                                             'status_text': {'type': 'string', 'required': False}},
                                'events': {}},
                'controller_help': {'host': 'external_view',
                                    'implementation': 'controller_help',
                                    'singleton': True,
                                    'default_anchor': 'world',
                                    'anchors': ['world'],
                                    'user_visibility_override': True,
                                    'properties': {'visible': {'type': 'boolean', 'default': True},
                                                   'settings_label': {'type': 'string',
                                                                      'default': ''}},
                                    'bindings': {'visible': {'type': 'boolean', 'required': False}},
                                    'events': {}},
                'control_frame': {'host': 'external_view',
                                  'implementation': 'control_frame',
                                  'singleton': True,
                                  'default_anchor': 'world',
                                  'anchors': ['world'],
                                  'user_visibility_override': True,
                                  'properties': {'visible': {'type': 'boolean', 'default': True},
                                                 'settings_label': {'type': 'string',
                                                                    'default': ''}},
                                  'bindings': {'visible': {'type': 'boolean', 'required': False}},
                                  'events': {}},
                'operation_trajectory': {'host': 'external_view',
                                         'implementation': 'operation_trajectory',
                                         'singleton': True,
                                         'default_anchor': 'world',
                                         'anchors': ['world'],
                                         'user_visibility_override': True,
                                         'properties': {'visible': {'type': 'boolean',
                                                                    'default': True},
                                                        'settings_label': {'type': 'string',
                                                                           'default': ''}},
                                         'bindings': {'visible': {'type': 'boolean',
                                                                  'required': False}},
                                         'events': {}}}}
WIRE = SPEC["wire"]
SPEC_CAPABILITY = WIRE["capability"] + "@sha256:85fc4ff0499ed3dbc3949778f9d5ba57806c2ab5632693be909108af1e4395b2"
LIMITS = SPEC["limits"]
WIRE_INTEGER_CONFORMANCE = SPEC["wire_integer_conformance"]
ANCHOR_SPECS = SPEC["anchors"]
ANCHORS = frozenset(SPEC["anchors"])
PRIMITIVES = SPEC["primitives"]
EXTERNAL_VIEW_TYPES = frozenset(
    name for name, primitive in PRIMITIVES.items()
    if primitive["host"] == "external_view"
)
